name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Lines
          plugin_lines: yes
          # Traffic
          plugin_traffic: yes
          # Habits
          plugin_habits: yes
          plugin_habits_from: 500
          config_timezone: America/New_York
          plugin_habits_facts: yes
          
          # Followup
          plugin_followup: yes
          # Topics
          #plugin_topics: yes
          #plugin_topics_sort: stars
          #plugin_topics_mode: mastered
          #plugin_topics_limit: 0
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
          plugin_languages_limit: 8
          # Iso Calendar
          plugin_isocalendar: yes
          # Self skip
          plugin_selfskip: yes
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params